config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :test, only: %i[index]

      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        registrations: 'api/v1/auth/registrations'
      }

      namespace :auth do
        resources :sessions, only: %i[index]
      end

      resources :users, only: %i[show], param: :user_name

      resources :stages, only: %i[new index create show edit update] do
        resource :user_stage_progresses, only: %i[create destroy]
      end
    end
  end

  resources :stages, only: %i[new index create show edit update]
  resources :users, only: %i[index show]
  root to: "stages#index"
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  include DeviseTokenAuth::Concerns::User

  validates :name, uniqueness: true

  has_many :user_stage_progresses
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
    def show
        user = User.find_by(name: params[:user_name])

        # すべてのステージのIDを取得
        stage_ids = Stage.pluck(:id)

        # ユーザーに関連するUserStageProgressを一度のクエリで取得
        user_stage_progresses = UserStageProgress.where(user_id: user.id, stage_id: stage_ids).index_by(&:stage_id)

        progresses = stage_ids.map do |stage_id|
            user_stage_progresses[stage_id]&.progress || -1
        end

        data = {
            progresses: progresses
        }

        render json: data.as_json
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
        @stages_count = Stage.count
    end
    
    def show
        @user = User.find(params[:id])
        @stages = Stage.all
        stage_ids = Stage.pluck(:id)

        # ユーザーに関連するUserStageProgressを一度のクエリで取得
        user_stage_progresses = UserStageProgress.where(user_id: @user.id, stage_id: stage_ids).index_by(&:stage_id)

        @progresses = stage_ids.map do |stage_id|
            user_stage_progresses[stage_id]&.progress || -1
        end
    end
end

app/views/users/index.html.erb
<p>ユーザーデータ一覧</p>
<table class="table table-hover table-inverse">
    <thead>
        <tr>
            <th>ユーザーID</th>
            <th>クリア状況</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td>
                    <%= link_to user.name, user_path(user.id) %>
                </td>
                <td>
                    <%= user.user_stage_progresses.count %> / <%= @stages_count %> 
                </td>
                <td>
                    
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<%= link_to "New Stage", new_stage_path, class: "btn btn-primary" %>

app/views/users/show.html.erb
<p>ユーザーID: <%= @user.name %>さんのデータ</p>
<p><%= link_to "一覧に戻る", users_path %></p>

<p>ステージ一覧</p>
<table class="table table-hover table-inverse">
    <thead>
        <tr>
            <th>ステージID</th>
            <th>ステージ</th>
            <th>スコア</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @stages.each do |stage| %>
            <tr>
                <td>
                    <%= stage.id %>
                </td>
                <td>
                    <%= display_stage(stage.board) %>
                </td>
                <td>
                    <%= @progresses[stage.id - 1] %> / 3
                </td>
                <td>
                    
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<%= link_to "New Stage", new_stage_path, class: "btn btn-primary" %>