config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :test, only: %i[index]

      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        registrations: 'api/v1/auth/registrations'
      }

      namespace :auth do
        resources :sessions, only: %i[index]
      end

      resources :users, only: %i[show], param: :user_name

      resources :stages, only: %i[new index create show edit update] do
        resource :user_stage_progresses, only: %i[create destroy]
      end
    end
  end

  resources :stages, only: %i[new index create show edit update]
  resources :users, only: %i[index show]
  root to: "stages#index"
end

app/models/stage.rb
class Stage < ApplicationRecord
  has_many :user_stage_progresses

  validate :square_board
  validate :can_solve

  private

  def square_board
    board_array = board.split("\r\n")
    length = board_array.length
    s_flag = false
    g_flag = false
  
    board_array.each_with_index do |row, i|
      unless row.length == length
        errors.add(:base, 'ステージは正方形でなければなりません')
        return
      end
  
      row.chars.each_with_index do |char, j|
        unless ['.', 'x', 'o', 'S', 'G', '@'].include?(char)
          errors.add(:base, "不正な文字が含まれています: #{char}")
        end
  
        if char == 'S'
          if s_flag
            errors.add(:base, '複数のスタート地点があります')
          else
            s_flag = true
          end
        end
  
        if char == 'G'
          if g_flag
            errors.add(:base, '複数のゴール地点があります')
          else
            g_flag = true
          end
        end
      end
    end
    errors.add(:base, 'スタート地点がありません') unless s_flag
    errors.add(:base, 'ゴール地点がありません') unless g_flag
  end

  def can_solve
    board_array = board.split("\r\n")
    length = board_array.length
    
    w = h = length
    sx = sy = nil
    gx = gy = nil
    board_array.each_with_index do |row, y|
      x = row.index('S')
      if x
        sx, sy = x, y
        break
      end
    end

    board_array.each_with_index do |row, y|
      x = row.index('G')
      if x
        gx, gy = x, y
        break
      end
    end

    if sx.nil? or gx.nil?
      errors.add(:base, 'スタートまたはゴール地点がありません')
      return
    end

    que = []
    dist = Array.new(length) { Array.new(length, -1) }
    dist[sy][sx] = 0
    que.push([sx, sy])

    while !que.empty?
      x, y = que.shift
      [[-1, 0], [1, 0], [0, -1], [0, 1]].each do |dx, dy|
        nx, ny = x, y
        loop do
          break if nx + dx < 0 || ny + dy < 0 || nx + dx >= w || ny + dy >= h
          break if board_array[ny + dy][nx + dx] == '#' || board_array[ny + dy][nx + dx] == 'x'
          if ['S', 'G', 'o'].include?(board_array[ny + dy][nx + dx])
            nx += dx
            ny += dy
            break
          end
          nx += dx
          ny += dy
        end
        if dist[ny][nx] == -1
          dist[ny][nx] = dist[y][x] + 1
          que.push([nx, ny])
        end
      end
    end
    if dist[gy][gx] == -1
      errors.add(:base, 'ゴールできません')
    end
  end
end

app/controllers/api/v1/stages_controller.rb
class Api::V1::StagesController < ApplicationController
    def show
        stage = Stage.find(params[:id])
        board = stage.board.split("\r\n")
        board = board.reverse
        height = board.length
        width = board[0].length
        data = {
            width: width,
            height: height,
            board: board
        }
        render json: data.as_json
    end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  def new
    @stage = Stage.new
    if params[:gen].present?
      @num = params[:num].to_i
      dist, board = get_stage(@num)
      @dist = dist
      @stage.board = board
    end
  end

  def create
    @stage = Stage.new(stage_params)
    if @stage.save
      redirect_to stages_path
    else
      render :new
    end
  end

  def index
    @stages = Stage.all
  end

  def show
    @stage = Stage.find(params[:id])
  end

  def edit
    @stage = Stage.find(params[:id])
  end

  def update
    @stage = Stage.find(params[:id])
    if @stage.update(stage_params)
      redirect_to stage_path(@stage.id)
    else
      render :edit
    end
  end

  private
  def stage_params
    params.require(:stage).permit(:board)
  end

  def solve(h, w, sx, sy, c)
    board = Array.new(h) { '.' * w }
    h.times do |i|
      w.times do |j|
        board[i][j] = c.chars.sample
      end
    end

    board[sy][sx] = 'S'
    board[h - 1][w - 1] = 'G'

    que = []
    dist = Array.new(h) { Array.new(w, -1) }
    dist[sy][sx] = 0
    que.push([sx, sy])

    while !que.empty?
      x, y = que.shift
      [[-1, 0], [1, 0], [0, -1], [0, 1]].each do |dx, dy|
        nx, ny = x, y
        loop do
          break if nx + dx < 0 || ny + dy < 0 || nx + dx >= w || ny + dy >= h
          break if board[ny + dy][nx + dx] == '#' || board[ny + dy][nx + dx] == 'x'
          if ['S', 'G', 'o'].include?(board[ny + dy][nx + dx])
            nx += dx
            ny += dy
            break
          end
          nx += dx
          ny += dy
        end
        if dist[ny][nx] == -1
          dist[ny][nx] = dist[y][x] + 1
          que.push([nx, ny])
        end
      end
    end
    [dist, board]
  end

  def get_stage(num)
    Random.srand(Time.now.to_i)
    c = "....................xx"
    h = w = num
    sx, sy = 0, 0
    gx, gy = h - 1, w - 1

    start_time = Time.now
    duration = 3.0
    border = 3

    loop do
      dist, board = solve(h, w, sx, sy, c)  # solveメソッドは適宜実装

      cnt = 0
      h.times do |i|
        w.times do |j|
          cnt += 1 if dist[i][j] != -1
        end
      end

      current_time = Time.now
      elapsed_time = current_time - start_time
      border = 4 if elapsed_time > duration
        
      next if cnt <= h * w / border || dist[gy][gx] <= h

      dist.each do |row|
        puts row.join(' ')
      end
      puts "\n"
      puts board
      board_string = board.map { |row| row }.join("\r\n")
      return dist[gy][gx], board_string
    end
  end
end

app/helpers/api/v1/stages_helper.rb
module Api::V1::StagesHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/edit.html.erb
<% if @stage.errors.any? %>
  <div id="error_explanation">
    <h3><%= @stage.errors.count %>件のエラーが発生しました:</h3>

    <ul>
    <% @stage.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model:@stage, local:true do |f| %>
    <div>
        <%= f.label :board %>
        <%= f.text_area :board, class: "form-control", rows: "10" %>
    </div>
    <div>
        <%= f.submit "Update Stage", class: "btn btn-success" %>
    </div>
<% end %>

<h1>.→<%= image_tag "IceFloor.PNG" %></h1>
<h1>x→<%= image_tag "IceBlock.PNG" %></h1>
<h1>o→<%= image_tag "SnowFloor.PNG" %></h1>
<h1>S→<%= image_tag "PenguinOnSnowFloor.PNG" %></h1>
<h1>G→<%= image_tag "GoalFloor.PNG" %></h1>
<h1>@→<%= image_tag "SnowBall.PNG" %></h1>

app/views/stages/index.html.erb
<p>ステージ一覧</p>
<table class="table table-hover table-inverse">
    <thead>
        <tr>
            <th>ステージID</th>
            <th>ステージ</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @stages.each do |stage| %>
            <tr>
                <td>
                    <%= stage.id %>
                </td>
                <td>
                    <%= display_stage(stage.board) %>
                </td>
                <td>
                    <%= link_to "編集する", stage_path(stage.id) %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<%= link_to "New Stage", new_stage_path, class: "btn btn-primary" %>

app/views/stages/new.html.erb
<p><%= link_to "< 一覧に戻る", stages_path %></p>

<% if @stage.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@stage.errors.count, "error") %> が発生しました:</h2>

    <ul>
    <% @stage.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model:@stage, local:true do |f| %>
    <div>
        <%= f.label :board %>
        <%= f.text_area :board, class: "form-control", rows: "10" %>
    </div>
    <div>
        <%= f.submit "Create Stage", class: "btn btn-success" %>
    </div>
<% end %>

<br>

<% if @stage.board.present? %>
    <%= display_stage(@stage.board) %>
    <h5><p>最善手: <%= @dist %>手</p></h5>
<% end %>

<%= form_with url:new_stage_path, method: :get do |f| %>
    <div>
        <%= f.hidden_field :gen, :value => true %>
    </div>
    <div>
        <%= f.label :num, "ステージの大きさ" %>
        <%= f.select :num, options_for_select(5..10, @num), class: "form-control" %>
    </div>
    <div>
        <%= f.submit "Auto-Generate Stage", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/stages/show.html.erb
<p><%= link_to "< 一覧に戻る", stages_path %></p>
<p><%= display_stage(@stage.board) %></p>
<p><%= link_to "編集", edit_stage_path(@stage.id) %></p>